import os
import json
from groq import Groq
from tools.harvester import tool_signal_harvester
from tools.analyst import tool_research_analyst
from tools.sender import tool_outreach_automated_sender

GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None

tools_schema = [
    {
        "type": "function",
        "function": {
            "name": "tool_signal_harvester",
            "description": "Fetches live signals for a company. Returns a JSON with signals.",
            "parameters": {
                "type": "object",
                "properties": {
                    "company_name": {
                        "type": "string",
                        "description": "Name of the target company"
                    }
                },
                "required": ["company_name"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "tool_research_analyst",
            "description": "Calls local model to process signals and ICP into an Account Brief.",
            "parameters": {
                "type": "object",
                "properties": {
                    "company_name": {
                        "type": "string",
                        "description": "Name of the target company"
                    },
                    "icp": {
                        "type": "string",
                        "description": "The Ideal Customer Profile description"
                    }
                },
                "required": ["company_name", "icp"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "tool_outreach_automated_sender",
            "description": "Drafts and sends an email via Resend API.",
            "parameters": {
                "type": "object",
                "properties": {
                    "brief": {
                        "type": "string",
                        "description": "The Account Brief generated by the analyst"
                    },
                    "company_name": {
                        "type": "string",
                        "description": "Name of the target company"
                    },
                    "recipient": {
                        "type": "string",
                        "description": "Email address of the target"
                    }
                },
                "required": ["brief", "company_name", "recipient"],
            },
        },
    }
]

async def run_outreach_flow(company_name: str, icp: str, recipient: str):
    """
    Generator function that yields SSE formatted string log events.
    """
    context_signals = None
    yield f"data: {json.dumps({'log': f'Starting outreach for {company_name}...'})}\n\n"
    
    if not client:
        yield f"data: {json.dumps({'log': 'MOCK MODE: GROQ_API_KEY missing.', 'type': 'warn'})}\n\n"
        yield f"data: {json.dumps({'log': 'Step 1: Harvesting data via Mock (Tavily API bypassed)...'})}\n\n"
        signals = tool_signal_harvester(company_name)
        
        yield f"data: {json.dumps({'log': 'Step 2: Qwen 2.5 is analyzing local signals...'})}\n\n"
        brief = await tool_research_analyst(signals, icp)
        
        yield f"data: {json.dumps({'log': 'Step 3: Sending email via Resend Mock...'})}\n\n"
        result = tool_outreach_automated_sender(brief, company_name, recipient)
        
        yield f"data: {json.dumps({'log': 'Outreach flow completed (Mock Mode).', 'result': result})}\n\n"
        return

    messages = [
        {"role": "system", "content": "You are the FireReach orchestrator. Use the given tools to 1) harvest signals, 2) generate an account brief, and 3) send an automated outreach email. You MUST call them in this order. Stop once the email is sent."},
        {"role": "user", "content": f"Begin the outreach sequence for company: {company_name}. The ICP is: {icp}. The target recipient email is: {recipient}."}
    ]

    try:
        for i in range(5):
            yield f"data: {json.dumps({'log': 'Agent reasoning (Groq Llama 3.1 8B)...'})}\n\n"
            response = client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=messages,
                tools=tools_schema,
                tool_choice="auto",
                parallel_tool_calls=False,
            )
            
            response_message = response.choices[0].message
            tool_calls = response_message.tool_calls

            if not tool_calls:
                yield f"data: {json.dumps({'log': 'Agent has concluded logic.' })}\n\n"
                break
                
            messages.append(response_message)
            
            for tool_call in tool_calls:
                function_name = tool_call.function.name
                arguments_str = tool_call.function.arguments
                
                try:
                    arguments = json.loads(arguments_str)
                except json.JSONDecodeError as err:
                    err_msg = f"ERROR: Malformed JSON from Groq for tool {function_name}: {err}. Halting."
                    yield f"data: {json.dumps({'log': err_msg, 'type': 'error'})}\n\n"
                    return
                
                yield f"data: {json.dumps({'log': f'Step {i+1}: Executing {function_name}'})}\n\n"
                
                if function_name == "tool_signal_harvester":
                    function_response = tool_signal_harvester(**arguments)
                    context_signals = function_response
                    
                    # Yield the extracted signals to the UI
                    signals_dump = json.dumps(context_signals.get('search_signals', []), indent=2)
                    yield f"data: {json.dumps({'log': f'Extracted Data:\\n{signals_dump}'})}\n\n"
                    
                elif function_name == "tool_research_analyst":
                    icp_val = arguments.get("icp", icp)
                    if not context_signals:
                        context_signals = {"company": company_name, "mode": "fallback", "search_signals": []}
                    
                    try:
                        yield f"data: {json.dumps({'log': 'Attempting local Ollama analysis...'})}\n\n"
                        function_response = await tool_research_analyst(signals=context_signals, icp=icp_val)
                    except Exception:
                        function_response = "Error contacting local Analyst (Ollama)."

                    # Fallback to Groq if local analyst failed
                    if "Error contacting local Analyst" in str(function_response):
                        yield f"data: {json.dumps({'log': 'Local Ollama unreachable. Falling back to Groq for analysis...', 'type': 'warn'})}\n\n"
                        fallback_prompt = f"As a sales expert, write a 2-paragraph Account Brief highlighting pain points for {company_name} based on these signals: {json.dumps(context_signals)} and this ICP: {icp_val}. Output ONLY the brief text."
                        fb_res = client.chat.completions.create(
                            model="llama-3.1-8b-instant",
                            messages=[{"role": "user", "content": fallback_prompt}]
                        )
                        function_response = fb_res.choices[0].message.content
                elif function_name == "tool_outreach_automated_sender":
                    function_response = tool_outreach_automated_sender(**arguments)
                    yield f"data: {json.dumps({'log': 'Final step complete.', 'result': function_response})}\n\n"
                else:
                    function_response = {"error": f"Unknown tool: {function_name}"}
                
                messages.append({
                    "tool_call_id": tool_call.id,
                    "role": "tool",
                    "name": function_name,
                    "content": json.dumps(function_response)
                })
                
    except Exception as e:
        yield f"data: {json.dumps({'log': f'Error in orchestration: {str(e)}', 'type': 'error'})}\n\n"
