import os
import json
from groq import Groq
from tools.harvester import tool_signal_harvester
from tools.analyst import tool_research_analyst
from tools.sender import tool_outreach_automated_sender

GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None

tools_schema = [
    {
        "type": "function",
        "function": {
            "name": "tool_signal_harvester",
            "description": "Fetches live signals for a company. Returns a JSON with signals.",
            "parameters": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Name of the target company"
                    }
                },
                "required": ["name"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "tool_research_analyst",
            "description": "Calls Groq AI to process signals and ICP into an Account Brief.",
            "parameters": {
                "type": "object",
                "properties": {
                    "company_name": {
                        "type": "string",
                        "description": "Name of the target company"
                    },
                    "icp": {
                        "type": "string",
                        "description": "The Ideal Customer Profile description"
                    }
                },
                "required": ["company_name", "icp"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "tool_outreach_automated_sender",
            "description": "Drafts and sends an email via Gmail SMTP.",
            "parameters": {
                "type": "object",
                "properties": {
                    "brief": {
                        "type": "string",
                        "description": "The Account Brief generated by the analyst"
                    },
                    "company_name": {
                        "type": "string",
                        "description": "Name of the target company"
                    },
                    "recipient": {
                        "type": "string",
                        "description": "Email address of the target"
                    }
                },
                "required": ["brief", "company_name", "recipient"],
            },
        },
    }
]

async def run_outreach_flow(company_name: str, icp: str, recipient: str):
    """
    Generator function that yields SSE formatted string log events.
    """
    context_signals = None
    yield f"data: {json.dumps({'log': f'Starting outreach for {company_name}...'})}\n\n"
    
    if not client:
        yield f"data: {json.dumps({'log': 'MOCK MODE: GROQ_API_KEY missing.', 'type': 'warn'})}\n\n"
        yield f"data: {json.dumps({'log': 'Step 1: Harvesting data via Mock (Tavily API bypassed)...'})}\n\n"
        signals = tool_signal_harvester(name=company_name)
        
        # Yield the extracted signals to the UI
        yield f"data: {json.dumps({'log': 'Signals extracted successfully.', 'signals': signals.get('search_signals', [])})}\n\n"
        
        yield f"data: {json.dumps({'log': 'Step 2: Analyzing signals with Groq...'})}\n\n"
        brief = tool_research_analyst(signals, icp)
        
        yield f"data: {json.dumps({'log': 'Step 3: Sending email via Gmail Mock...'})}\n\n"
        result = tool_outreach_automated_sender(brief, company_name, recipient)
        
        yield f"data: {json.dumps({'log': 'Outreach flow completed (Mock Mode).', 'result': result})}\n\n"
        return

    messages = [
        {"role": "system", "content": "You are the FireReach orchestrator. Use the given tools to 1) harvest signals, 2) generate an account brief, and 3) send an automated outreach email. You MUST call them in this order. Stop once the email is sent."},
        {"role": "user", "content": f"Begin the outreach sequence for company: {company_name}. The ICP is: {icp}. The target recipient email is: {recipient}."}
    ]

    try:
        for i in range(5):
            yield f"data: {json.dumps({'log': 'Agent reasoning (Groq Llama 3.1 8B)...'})}\n\n"
            response = client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=messages,
                tools=tools_schema,
                tool_choice="auto",
                parallel_tool_calls=False,
            )
            
            response_message = response.choices[0].message
            tool_calls = response_message.tool_calls

            if not tool_calls:
                yield f"data: {json.dumps({'log': 'Agent has concluded logic.' })}\n\n"
                break
                
            messages.append(response_message)
            
            for tool_call in tool_calls:
                function_name = tool_call.function.name
                arguments_str = tool_call.function.arguments
                
                try:
                    arguments = json.loads(arguments_str)
                except json.JSONDecodeError as err:
                    err_msg = f"ERROR: Malformed JSON from Groq for tool {function_name}: {err}. Halting."
                    yield f"data: {json.dumps({'log': err_msg, 'type': 'error'})}\n\n"
                    return
                
                yield f"data: {json.dumps({'log': f'Step {i+1}: Executing {function_name}'})}\n\n"
                
                if function_name == "tool_signal_harvester":
                    function_response = tool_signal_harvester(**arguments)
                    context_signals = function_response
                    
                    # Yield the extracted signals to the UI
                    yield f"data: {json.dumps({'log': 'Signals extracted successfully.', 'signals': context_signals.get('search_signals', [])})}\n\n"
                    
                elif function_name == "tool_research_analyst":
                    icp_val = arguments.get("icp", icp)
                    if not context_signals:
                        context_signals = {"company": company_name, "mode": "fallback", "search_signals": []}
                    
                    yield f"data: {json.dumps({'log': 'Analyzing signals with Groq...'})}\n\n"
                    function_response = tool_research_analyst(signals=context_signals, icp=icp_val)
                elif function_name == "tool_outreach_automated_sender":
                    function_response = tool_outreach_automated_sender(**arguments)
                    yield f"data: {json.dumps({'log': 'Final step complete.', 'result': function_response})}\n\n"
                else:
                    function_response = {"error": f"Unknown tool: {function_name}"}
                
                messages.append({
                    "tool_call_id": tool_call.id,
                    "role": "tool",
                    "name": function_name,
                    "content": json.dumps(function_response)
                })
                
    except Exception as e:
        yield f"data: {json.dumps({'log': f'Error in orchestration: {str(e)}', 'type': 'error'})}\n\n"
